version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: alias-game
    ports:
      - "3000:3000"
    environment:
      JWT_SECRET: ${JWT_SECRET}
      MONGODB_URI: ${MONGO_URI}